### ISSUE TITLE
Submit this docset to Dash

### ISSUE THREAD

**Issue by tokou** [obstschale/octave-docset#2]
Hi,

You should submit this docset to the [Dash User Contributions](https://github.com/Kapeli/Dash-User-Contributions) repo. This way, Dash users can find it directly from within Dash, under the "User Contributed" section.

Cheers

**Comment by obstschale** [comment]
You're right. I tried it once but it didn't meet the requirements. After that I didn't used octave anymore. But I will try to fix that and submit it soon :+1:

**Comment by obstschale** [comment]
I sent a new pull request: Kapeli/Dash-User-Contributions#351

**Comment by tokou** [comment]
Thanks a lot.
